version: '4'

services:
  app:
    image: department:latest
    container_name: department
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/departmentdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: departmentdb
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge